### ISSUE TITLE
Possibly Broken?

### ISSUE THREAD

**Issue by nickwinn** [linnit/Soundcloud-Downloader#26]
This used to work on a Centos 6 distro. I've since moved to Centos 7 and tried it without any luck. Is this a known issue?

[root@iris id3-py-1.2]# soundcloud-downloader.py -v "https://soundcloud.com/roywoodsofficial/drama-feat-drake"
Traceback (most recent call last):
  File "/usr/local/bin/soundcloud-downloader.py", line 138, in <module>
    download = SoundCloudDownload(args.SOUND_URL, verbose, tags)
  File "/usr/local/bin/soundcloud-downloader.py", line 27, in **init**
    self.streamURLlist = self.getStreamURLlist(self.url)
  File "/usr/local/bin/soundcloud-downloader.py", line 57, in getStreamURLlist
    waveform_url = track['waveform_url']
KeyError: 'waveform_url'

**Comment by umbreon222** [comment]
https://developers.soundcloud.com/blog/introducing-javascript-sdk-3-0-0 SDK 3.0 is the problem. I'm working on a fix in my forked version.

**Comment by rouslanovitch** [comment]
looks like now the script do not download even downloadable songs: 

python soundcloud-downloader.py https://soundcloud.com/les-gordon/les-gordon-ftlenparrot-the-distance
Downloading: Les Gordon FtLenparrot - The Distance.mp3
ERROR: Author has not set song to streamable, so it cannot be downloaded

**Comment by umbreon222** [comment]
I just fixed it in my new release, check my fork https://github.com/umbreon222/Python-SoundcloudDownloader

**Comment by flyingrub** [comment]
hey guys why not use my version ? 
https://github.com/flyingrub/scdl
