### ISSUE TITLE
No module named soundcloud

### ISSUE THREAD

**Issue by themightyoarfish** [linnit/Soundcloud-Downloader#28]
Requirements don't specify that `soundcloud` module is a dependency.

**Comment by wierzba3** [comment]
I'm having the same problem. Where is this soundcloud module that it is trying to import?

**Comment by themightyoarfish** [comment]
You can install it via pip, it's just that it should be listed as a dependency.

**Comment by kiranshahi** [comment]
pip install soundcloud
